language: node_js
node_js:
  - "node"

notifications:
  email: false

cache:
  directories:
    - node_modules

before_script:
  - npm build
  - npm start --silent &

script:
  # run E2E tests:
  - $(npm bin)/cypress run --record

deploy:
  provider: surge
  project: ./static/
  domain: sex-education.surge.sh
  cleanup: false
